import { UserResponse } from "../src/interfaces/searchResponse";
import { User } from "../src/interfaces/user";

export const mockUsers: User[] = [
  {
    avatar_url: "https://avatars.githubusercontent.com/u/12437?v=4",
    followers: 10,
    following: 1,
    id: 12437,
    login: "juan",
    name: "Juan Pablo Moreno G",
    public_repos: 1,
    html_url: "https://github.com/juan",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/138401?v=4",
    followers: 2557,
    following: 26,
    id: 138401,
    login: "jbenet",
    name: "Juan Benet",
    public_repos: 286,
    html_url: "https://github.com/jbenet",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/15987317?v=4",
    followers: 1666,
    following: 823,
    id: 15987317,
    login: "juandc",
    name: "Juan David Castro",
    public_repos: 80,
    html_url: "https://github.com/juandc",
  },
];

export const mockUserDetail: User = {
  avatar_url: "https://avatars.githubusercontent.com/u/15987317?v=4",
  followers: 1666,
  following: 823,
  id: 15987317,
  login: "juandc",
  name: "Juan David Castro",
  public_repos: 80,
  html_url: "https://github.com/juandc",
};

export const mockUserDetailResponse: UserResponse = {
  login: "juandc",
  id: 15987317,
  node_id: "MDQ6VXNlcjE1OTg3MzE3",
  avatar_url: "https://avatars.githubusercontent.com/u/15987317?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/juandc",
  html_url: "https://github.com/juandc",
  followers_url: "https://api.github.com/users/juandc/followers",
  following_url: "https://api.github.com/users/juandc/following{/other_user}",
  gists_url: "https://api.github.com/users/juandc/gists{/gist_id}",
  starred_url: "https://api.github.com/users/juandc/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/juandc/subscriptions",
  organizations_url: "https://api.github.com/users/juandc/orgs",
  repos_url: "https://api.github.com/users/juandc/repos",
  events_url: "https://api.github.com/users/juandc/events{/privacy}",
  received_events_url: "https://api.github.com/users/juandc/received_events",
  type: "User",
  site_admin: false,
  score: 1,
};

export const mockUsersResponse: UserResponse[] = [
  {
    login: "juan",
    id: 12437,
    node_id: "MDQ6VXNlcjEyNDM3",
    avatar_url: "https://avatars.githubusercontent.com/u/12437?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/juan",
    html_url: "https://github.com/juan",
    followers_url: "https://api.github.com/users/juan/followers",
    following_url: "https://api.github.com/users/juan/following{/other_user}",
    gists_url: "https://api.github.com/users/juan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/juan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/juan/subscriptions",
    organizations_url: "https://api.github.com/users/juan/orgs",
    repos_url: "https://api.github.com/users/juan/repos",
    events_url: "https://api.github.com/users/juan/events{/privacy}",
    received_events_url: "https://api.github.com/users/juan/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
  {
    login: "jbenet",
    id: 138401,
    node_id: "MDQ6VXNlcjEzODQwMQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/138401?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jbenet",
    html_url: "https://github.com/jbenet",
    followers_url: "https://api.github.com/users/jbenet/followers",
    following_url: "https://api.github.com/users/jbenet/following{/other_user}",
    gists_url: "https://api.github.com/users/jbenet/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jbenet/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jbenet/subscriptions",
    organizations_url: "https://api.github.com/users/jbenet/orgs",
    repos_url: "https://api.github.com/users/jbenet/repos",
    events_url: "https://api.github.com/users/jbenet/events{/privacy}",
    received_events_url: "https://api.github.com/users/jbenet/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
  {
    login: "juandc",
    id: 15987317,
    node_id: "MDQ6VXNlcjE1OTg3MzE3",
    avatar_url: "https://avatars.githubusercontent.com/u/15987317?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/juandc",
    html_url: "https://github.com/juandc",
    followers_url: "https://api.github.com/users/juandc/followers",
    following_url: "https://api.github.com/users/juandc/following{/other_user}",
    gists_url: "https://api.github.com/users/juandc/gists{/gist_id}",
    starred_url: "https://api.github.com/users/juandc/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/juandc/subscriptions",
    organizations_url: "https://api.github.com/users/juandc/orgs",
    repos_url: "https://api.github.com/users/juandc/repos",
    events_url: "https://api.github.com/users/juandc/events{/privacy}",
    received_events_url: "https://api.github.com/users/juandc/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
];
